  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
#        - run:
#          name: curl test with invalid host name
#          command: curl www.abcdedasbc.com
#        - run:
#          name: curl test with 404 not found response
#          command: curl https://circleci.com/apiapiapi
